### ISSUE TITLE
Can't get past "lets go" button 

### ISSUE THREAD

**Issue by imjakechapman** [adampatterson/Tentacle#38]
Set up virtualhost via VirtualHostX and using MAMP's apache server.
uploaded all files to sites directory folder, navigated to root folder and nothing. 
Only untill I redirected my browser to tentacle.dev/setup/index.php would they beginning of installation would start, but after clicking the "let's go" button. I would get a 404 error

"NOT FOUND - The requested URL /setup/action/agree/ was not found on this server."

**Comment by adampatterson** [comment]
Do you have mod_rewrie enabled, that is a must.

Also could you check and see if you have a .htaccess file?

https://github.com/adampatterson/Tentacle/blob/dev/.htaccess

I have done some updates requarding a 404 after install is complete and fixed an incorrect redirect from the root.

Try to re-download the zip and see if you have better luck.

https://github.com/adampatterson/Tentacle/zipball/dev

**Comment by adampatterson** [comment]
Hey Jake,

I tested with VirtualHostX and was unable to get the app working as well.

I am not sure why this is but there is a slim chance it will be an issue for most users.

If you would like try running the app from a regular MAMP install, or even a web host.

Cheers!
